---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: retail-store
  title: Retail Store Platform
  description: "E-commerce microservices platform running on Amazon EKS via GitOps (ArgoCD + Helm)"
  tags:
    - ecommerce
    - microservices
    - eks
  links:
    - url: https://github.com/tranduyloc895/idp-microservices
      title: Source Monorepo
      icon: github
    - url: https://github.com/tranduyloc895/idp-gitops
      title: GitOps Repo
      icon: github
spec:
  owner: platform-team
