---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-bench
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kube-bench
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-bench
  labels:
    app.kubernetes.io/name: kube-bench
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-bench
  labels:
    app.kubernetes.io/name: kube-bench
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-bench
subjects:
  - kind: ServiceAccount
    name: kube-bench
    namespace: monitoring
